---
global:
  pattern: quarkus-coffeeshop

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  git:
    hostname: github.com
    account: hybrid-cloud-demos
    username: hybrid-cloud-demos
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  imageregistry:
    account: hybridcloudpatterns
    hostname: quay.io
    type: quay

  homeofficeBackend:
    revision: main
    imageTag: latest

  homeofficeIngress:
    revision: master
    imageTag: latest

  homeofficeUI:
    revision: master
    imageTag: latest

  quarkuscoffeeshopBarista:
    revision: main
    imageTag: latest

  quarkuscoffeeshopCounter:
    revision: 5.0.3-SNAPSHOT
    imageTag: latest

  quarkuscoffeeshopCustomerloyalty:
    revision: main
    imageTag: latest

  quarkuscoffeeshopCustomermocker:
    revision: master
    imageTag: latest

  quarkuscoffeeshopInventory:
    revision: '5.0.0-SNAPSHOT'
    imageTag: latest

  quarkuscoffeeshopKitchen:
    revision: main
    # revision: '5.0.0-SNAPSHOT'
    imageTag: latest

  quarkuscoffeeshopMajesticMonolith:
    revision: master
    imageTag: latest

  quarkuscoffeeshopWeb:
    revision: '5.0.3-SNAPSHOT'
    imageTag: latest

main:
  clusterGroupName: hub
  gitops:
    channel: stable

