---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeoffice-ingress
  labels:
    app: homeoffice-ingress
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica_count.ingress }}
  selector:
    matchLabels:
      app: homeoffice-ingress
  template:
    metadata:
      name: homeoffice-ingress-deployment
      labels:
        app: homeoffice-ingress
        release: {{ .Release.Name }}
        app.kubernetes.io/component: homeoffice-ingress
        app.kubernetes.io/instance: homeoffice-ingress
        app.kubernetes.io/part-of: quarkus-cafe
        quarkus-cafe: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: homeoffice-ingress
          image: {{ .Values.global.imageregistry.hostname }}/{{ .Values.global.imageregistry.account }}/homeoffice-ingress:{{ .Values.global.homeofficeIngress.imageTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: {{ .Values.kafka_cluster_name }}-kafka-bootstrap:9092
            - name: POSTGRESQL_JDBC_URL
              value: 'jdbc:postgresql://homeofficedb-primary.{{ .Values.projectnamespace }}.svc:5432/homeofficedb?currentSchema=homeoffice'
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: homeofficedb-pguser-homeofficeuser
                  key: user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homeofficedb-pguser-homeofficeuser
                  key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeeshop-homeoffice-ui
  labels:
    app: homeoffice-ui
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica_count.ui }}
  selector:
    matchLabels:
      app: homeoffice-ui
  template:
    metadata:
      name: homeoffice-ui-deployment
      labels:
        app: homeoffice-ui
        release: {{ .Release.Name }}
        app.kubernetes.io/component: homeoffice-ui
        app.kubernetes.io/instance: homeoffice-ui
        app.kubernetes.io/part-of: quarkus-cafe
        quarkus-cafe: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: homeoffice-ingress
          image: {{ .Values.global.imageregistry.hostname }}/{{ .Values.global.imageregistry.account }}/quarkuscoffeeshop-homeoffice-ui:{{ .Values.global.homeofficeUI.imageTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REACT_APP_GRAPHQL_ENDPOINT
              value: 'http://quarkuscoffeeshop-backend.coffeeshop-homeoffice.svc:8080/graphql'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeeshop-homeoffice-backend
  labels:
    app: homeoffice-backend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica_count.backend }}
  selector:
    matchLabels:
      app: homeoffice-backend
  template:
    metadata:
      name: homeoffice-backend-deployment
      labels:
        app: homeoffice-backend
        release: {{ .Release.Name }}
        app.kubernetes.io/component: homeoffice-backend
        app.kubernetes.io/instance: homeoffice-backend
        app.kubernetes.io/part-of: quarkus-cafe
        quarkus-cafe: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: homeoffice-backend
          image: {{ .Values.global.imageregistry.hostname }}/{{ .Values.global.imageregistry.account }}/homeoffice-backend:{{ .Values.global.homeofficeBackend.imageTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: {{ .Values.kafka_cluster_name }}-kafka-bootstrap:9092
            - name: POSTGRESQL_JDBC_URL
              value: 'jdbc:postgresql://homeofficedb-primary.{{ .Values.projectnamespace }}.svc:5432/homeofficedb?currentSchema=homeoffice'
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: homeofficedb-pguser-homeofficeuser
                  key: user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homeofficedb-pguser-homeofficeuser
                  key: password
