piVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: coffeeshopdb-homeoffice
spec:
  port: 5432
  dataSource:
    pgbackrest:
      stanza: db
  standby:
    enabled: true
  userInterface:
    pgAdmin:
      service:
        type: ClusterIP
      replicas: 1
  proxy:
    pgBouncer:
      port: 5432
      service:
        type: ClusterIP
      replicas: 1
  backups:
    pgbackrest:
      restore:
        enabled: false
  service:
    type: ClusterIP
  patroni:
    leaderLeaseDurationSeconds: 30
    port: 8008
    switchover:
      type: Switchover
    syncPeriodSeconds: 10
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: l0Gi
      replicas: 1
  postgresVersion: 13
